### ISSUE TITLE
Input stream error

### ISSUE THREAD

**Issue by m-grohs** [mienaiyami/ytdl-gui#1]
### Question

as of late it seems like youtube changed something and when trying to use the app for mp3 it only throws the error:
```
Error: Input stream error: Status code: 403
```
just wanted to let you know.

**Comment by mienaiyami** [comment]
Thanks for informing me. I have been too busy with other works that I can't even give time to my main project, Yomikiru. So unfortunately, it won't be fixed for a long time.
I recommend using another open-source app, "open video downloader" (also known as youtube-dl-gui). Or stacher.io (not open source).
